# -*- coding: utf-8 -*-
"""NewLinkWireless_CienciaDatosII.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uekjWCZE0yDpY_-j_--kpersbpkSqnHp

# Proyecto Final - Ciencia de Datos II
## Predicción de cancelación de clientes - NewLinkWireless

### 1. Importación de librerías
"""

import pandas as pd
import numpy as np

print("Librerías cargadas correctamente.")

df = pd.read_csv("/content/dataset_cancelacion_newlinkwireless.csv")

print("Dataset cargado correctamente.")
print("Cantidad de filas:", df.shape[0])
print("Cantidad de columnas:", df.shape[1])

df.head()

"""### 2. Exploración inicial del dataset

Antes de realizar la limpieza, se analiza la estructura y calidad del dataset para identificar valores nulos, registros duplicados, tipos de datos e inconsistencias.
"""

df.info()

print("Valores nulos por columna:")
print(df.isnull().sum())

print("\nTotal de valores nulos:", df.isnull().sum().sum())

duplicados = df.duplicated().sum()

print("Registros duplicados:", duplicados)

df.describe()

columnas_categoricas = df.select_dtypes(include="object").columns

for columna in columnas_categoricas:
    print(f"\n--- {columna} ---")
    print(df[columna].value_counts())

print("Tickets abiertos mayores al total:")
print((df["tickets_abiertos"] > df["cantidad_tickets"]).sum())

print("\nTickets críticos mayores al total:")
print((df["tickets_criticos"] > df["cantidad_tickets"]).sum())

print("\nSaldos pendientes negativos:")
print((df["saldo_pendiente"] < 0).sum())

print("\nPrecios negativos o iguales a cero:")
print((df["precio_contratado"] <= 0).sum())

print("\nAntigüedad negativa:")
print((df["antiguedad_meses"] < 0).sum())

print("\nValores distintos de 0 y 1 en cancelo_servicio:")
print(df.loc[~df["cancelo_servicio"].isin([0, 1]), "cancelo_servicio"].count())

"""### 3. Limpieza de datos

A partir de la exploración inicial se verificó la calidad del dataset mediante la revisión de valores nulos, registros duplicados, tipos de datos, categorías e inconsistencias lógicas.

El dataset presentó una buena calidad general. Sin embargo, se identificaron inconsistencias en las variables relacionadas con tickets, específicamente registros donde la cantidad de tickets abiertos o críticos era superior a la cantidad total de tickets. Estas inconsistencias serán corregidas antes de continuar con el análisis.
"""

inconsistencias_tickets = df[
    (df["tickets_abiertos"] > df["cantidad_tickets"]) |
    (df["tickets_criticos"] > df["cantidad_tickets"])
]

inconsistencias_tickets[
    ["id_servicio", "cantidad_tickets", "tickets_abiertos", "tickets_criticos"]
]

"""#### Corrección de inconsistencias en tickets

Se identificaron tres registros con inconsistencias lógicas en las variables relacionadas con tickets. Debido a que la cantidad de tickets abiertos y críticos no puede superar la cantidad total de tickets registrados, se ajustaron estos valores tomando como límite máximo la cantidad total de tickets de cada servicio.
"""

df["tickets_abiertos"] = df[
    ["tickets_abiertos", "cantidad_tickets"]
].min(axis=1)

df["tickets_criticos"] = df[
    ["tickets_criticos", "cantidad_tickets"]
].min(axis=1)

print("Inconsistencias corregidas.")

print(
    "Tickets abiertos mayores al total:",
    (df["tickets_abiertos"] > df["cantidad_tickets"]).sum()
)

print(
    "Tickets críticos mayores al total:",
    (df["tickets_criticos"] > df["cantidad_tickets"]).sum()
)

"""#### Verificación final de consistencia

Después de corregir las inconsistencias detectadas en los tickets, se realizó una verificación adicional de las variables financieras y operativas para confirmar la coherencia del dataset.
"""

# Verificar coherencia de las variables financieras
diferencia_saldo = (
    df["monto_facturado"] -
    df["monto_pagado"] -
    df["saldo_pendiente"]
).abs()

print(
    "Saldos pendientes inconsistentes:",
    (diferencia_saldo > 0.01).sum()
)

print(
    "Monto pagado mayor al facturado:",
    (df["monto_pagado"] > df["monto_facturado"]).sum()
)

print(
    "Facturas vencidas mayores al total:",
    (df["facturas_vencidas"] > df["cantidad_facturas"]).sum()
)

print(
    "Valores negativos en cantidad de tickets:",
    (df["cantidad_tickets"] < 0).sum()
)

print(
    "Valores negativos en días de atraso:",
    (df["dias_atraso_promedio"] < 0).sum()
)

"""#### Resultado de la limpieza

Después de realizar las verificaciones de calidad y consistencia, se corrigieron tres registros que presentaban inconsistencias en las variables `tickets_abiertos` y `tickets_criticos`.

También se comprobó que no existen saldos pendientes inconsistentes, montos pagados superiores a los facturados, facturas vencidas superiores al total de facturas, cantidades negativas de tickets ni valores negativos en los días promedio de atraso.

Después de estas correcciones y verificaciones, el dataset queda preparado para continuar con el Análisis Exploratorio de Datos (EDA).
"""

df.to_csv(
    "/content/dataset_cancelacion_newlinkwireless_limpio.csv",
    index=False
)

print("Dataset limpio guardado correctamente.")
print("Dimensiones finales:", df.shape)

"""### 4. Análisis Exploratorio de Datos (EDA)

En esta etapa se analizará el comportamiento de las principales variables del dataset y su relación con la cancelación del servicio.

El objetivo es identificar patrones que puedan ayudar a comprender qué características están asociadas con una mayor probabilidad de cancelación.

#### Distribución de cancelación del servicio

Se analizará la cantidad de servicios cancelados y no cancelados para conocer cómo se distribuye la variable objetivo dentro del dataset.
"""

import matplotlib.pyplot as plt

conteo_cancelacion = df["cancelo_servicio"].value_counts().sort_index()

plt.figure(figsize=(6, 4))

plt.bar(
    ["No canceló", "Canceló"],
    conteo_cancelacion.values
)

plt.title("Distribución de cancelación del servicio")
plt.xlabel("Estado de cancelación")
plt.ylabel("Cantidad de servicios")

plt.show()

"""#### Interpretación

De los 1,000 servicios analizados, aproximadamente el **20.1% corresponde a servicios cancelados**, mientras que el **79.9% no presenta cancelación**.

Esto evidencia un desbalance entre las clases de la variable objetivo. Por esta razón, al evaluar los modelos de clasificación no se utilizará únicamente el Accuracy, sino también métricas como Precision, Recall y F1-Score, especialmente para evaluar la capacidad del modelo de identificar correctamente las cancelaciones.

#### Cancelación por tipo de servicio

Se analizará el porcentaje de cancelación según el tipo de servicio para identificar si existen diferencias entre fibra óptica, cable, inalámbrico y enlace dedicado.
"""

cancelacion_servicio = (
    df.groupby("tipo_servicio")["cancelo_servicio"]
    .mean()
    .sort_values(ascending=False)
    * 100
)

plt.figure(figsize=(8, 4))

plt.bar(
    cancelacion_servicio.index,
    cancelacion_servicio.values
)

plt.title("Porcentaje de cancelación por tipo de servicio")
plt.xlabel("Tipo de servicio")
plt.ylabel("Porcentaje de cancelación")

plt.xticks(rotation=20)

plt.show()

print(cancelacion_servicio.round(2))

"""#### Cantidad de tickets según cancelación

Se analizará la cantidad promedio de tickets de soporte registrados para los servicios cancelados y no cancelados.

Este análisis permite observar si los clientes que presentan una mayor cantidad de solicitudes de soporte también muestran una mayor tendencia a cancelar el servicio.
"""

promedio_tickets = (
    df.groupby("cancelo_servicio")["cantidad_tickets"]
    .mean()
)

plt.figure(figsize=(6, 4))

barras = plt.bar(
    ["No canceló", "Canceló"],
    promedio_tickets.values
)

plt.title("Promedio de tickets según cancelación")
plt.xlabel("Estado de cancelación")
plt.ylabel("Cantidad promedio de tickets")

for barra in barras:
    altura = barra.get_height()
    plt.text(
        barra.get_x() + barra.get_width() / 2,
        altura,
        f"{altura:.2f}",
        ha="center",
        va="bottom"
    )

plt.show()

print(promedio_tickets)

"""#### Interpretación

Los servicios cancelados registraron un promedio de aproximadamente **4.72 tickets de soporte**, mientras que los servicios que no fueron cancelados presentaron un promedio de **2.17 tickets**.

Esto muestra que, dentro del dataset analizado, los servicios cancelados acumularon más del doble de tickets de soporte en promedio. El resultado sugiere una asociación entre una mayor cantidad de solicitudes de soporte y la cancelación del servicio.

Por lo tanto, `cantidad_tickets` puede ser una variable relevante para el modelo predictivo y para identificar clientes que podrían requerir mayor atención.

#### Facturas vencidas según cancelación

Se analizará la cantidad promedio de facturas vencidas para los servicios cancelados y no cancelados.

Este análisis permite observar si los clientes con más facturas vencidas presentan una mayor tendencia a cancelar el servicio.
"""

promedio_facturas_vencidas = (
    df.groupby("cancelo_servicio")["facturas_vencidas"]
    .mean()
)

plt.figure(figsize=(6, 4))

barras = plt.bar(
    ["No canceló", "Canceló"],
    promedio_facturas_vencidas.values
)

plt.title("Promedio de facturas vencidas según cancelación")
plt.xlabel("Estado de cancelación")
plt.ylabel("Promedio de facturas vencidas")

for barra in barras:
    altura = barra.get_height()
    plt.text(
        barra.get_x() + barra.get_width() / 2,
        altura,
        f"{altura:.2f}",
        ha="center",
        va="bottom"
    )

plt.show()

print(promedio_facturas_vencidas)

"""#### Interpretación

Los servicios cancelados presentaron un promedio de aproximadamente **4.21 facturas vencidas**, mientras que los servicios no cancelados registraron un promedio de **2.36**.

Dentro del dataset analizado, se observa una asociación entre una mayor cantidad de facturas vencidas y la cancelación del servicio. Esto indica que el comportamiento de pago puede aportar información relevante para identificar servicios con mayor riesgo de cancelación.

Por esta razón, `facturas_vencidas` se considera una variable de interés para el posterior modelo de clasificación.

#### Días promedio de atraso según cancelación

Se analizará el promedio de días de atraso de los servicios cancelados y no cancelados.

Este análisis permite observar si los clientes que presentan mayores retrasos en sus pagos también muestran una mayor tendencia a cancelar el servicio.
"""

promedio_dias_atraso = (
    df.groupby("cancelo_servicio")["dias_atraso_promedio"]
    .mean()
)

plt.figure(figsize=(6, 4))

barras = plt.bar(
    ["No canceló", "Canceló"],
    promedio_dias_atraso.values
)

plt.title("Días promedio de atraso según cancelación")
plt.xlabel("Estado de cancelación")
plt.ylabel("Días promedio de atraso")

for barra in barras:
    altura = barra.get_height()
    plt.text(
        barra.get_x() + barra.get_width() / 2,
        altura,
        f"{altura:.2f}",
        ha="center",
        va="bottom"
    )

plt.show()

print(promedio_dias_atraso)

"""#### Interpretación

Los servicios que fueron cancelados presentaron un atraso promedio de aproximadamente **13.64 días**, mientras que los servicios no cancelados registraron un promedio de **5.99 días**.

La diferencia observada muestra que, dentro del dataset analizado, los servicios cancelados presentan retrasos de pago considerablemente mayores. Esto sugiere que `dias_atraso_promedio` puede aportar información relevante para identificar patrones asociados con la cancelación.

Este comportamiento también complementa el resultado observado en las facturas vencidas, mostrando que las variables relacionadas con el cumplimiento de pagos pueden ser importantes para el análisis predictivo.

#### Antigüedad del cliente y cancelación

La antigüedad del servicio puede ayudar a determinar si existe una diferencia en el comportamiento de cancelación entre clientes recientes y clientes con mayor permanencia en la empresa.
"""

# Promedio de antigüedad según cancelación
antiguedad_cancelacion = df.groupby(
    "cancelo_servicio"
)["antiguedad_meses"].agg(["mean", "median", "min", "max"])

antiguedad_cancelacion

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8, 5))

sns.boxplot(
    data=df,
    x="cancelo_servicio",
    y="antiguedad_meses"
)

plt.title("Antigüedad del servicio según cancelación")
plt.xlabel("Canceló el servicio (0 = No, 1 = Sí)")
plt.ylabel("Antigüedad (meses)")

plt.show()

"""#### Interpretación

Los servicios que no fueron cancelados presentan una antigüedad promedio de aproximadamente **32.05 meses**, mientras que los servicios cancelados registran un promedio de **19.85 meses**.

La mediana también refleja esta diferencia: **31 meses** para los servicios no cancelados frente a **18 meses** para los cancelados.

Dentro del dataset analizado, estos resultados muestran una asociación entre una menor antigüedad y la cancelación del servicio. Por lo tanto, `antiguedad_meses` puede ser una variable relevante para el modelo predictivo. Este resultado representa una asociación y no implica necesariamente una relación causal.

### 5. Preparación de los datos para Machine Learning

Para desarrollar los modelos de clasificación, se utiliza `cancelo_servicio` como variable objetivo, donde **0 representa un servicio no cancelado y 1 un servicio cancelado**.

La variable `id_servicio` se excluye del entrenamiento debido a que funciona únicamente como identificador y no representa una característica útil para predecir la cancelación.

Las variables categóricas, como el tipo de cliente, tipo de servicio y plan contratado, se transforman mediante **One-Hot Encoding**, permitiendo que puedan ser utilizadas por los algoritmos de Machine Learning.

Posteriormente, el dataset se divide en un conjunto de **entrenamiento (80%)** y un conjunto de **prueba (20%)**. La división se realiza de forma estratificada para conservar aproximadamente la misma proporción de servicios cancelados y no cancelados en ambos conjuntos.
"""

X = df.drop(columns=["cancelo_servicio", "id_servicio"])
y = df["cancelo_servicio"]

print("Dimensiones de X:", X.shape)
print("Dimensiones de y:", y.shape)

print("\nDistribución de la variable objetivo:")
print(y.value_counts())

print("\nPorcentaje:")
print(y.value_counts(normalize=True) * 100)

"""#### Separación de variables categóricas y numéricas

El dataset contiene variables numéricas y categóricas. Para poder utilizar correctamente los modelos de clasificación, se identificarán ambos tipos de variables.

Las variables categóricas deberán transformarse a valores numéricos antes del entrenamiento, mientras que las variables numéricas podrán conservarse con sus valores originales.
"""

columnas_categoricas = [
    "tipo_cliente",
    "tipo_servicio",
    "plan"
]

columnas_numericas = [
    columna for columna in X.columns
    if columna not in columnas_categoricas
]

print("Variables categóricas:")
print(columnas_categoricas)

print("\nVariables numéricas:")
print(columnas_numericas)

"""#### Preprocesamiento de variables categóricas

Las variables categóricas deben transformarse a una representación numérica para que puedan ser utilizadas por los modelos de clasificación.

Para este proceso se utilizará One-Hot Encoding, una técnica que crea columnas binarias a partir de cada categoría, evitando asignar un orden artificial entre los valores.
"""

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

preprocesador = ColumnTransformer(
    transformers=[
        (
            "categoricas",
            OneHotEncoder(handle_unknown="ignore"),
            columnas_categoricas
        ),
        (
            "numericas",
            StandardScaler(),
            columnas_numericas
        )
    ]
)

print("Preprocesador preparado correctamente.")

"""#### División del dataset en entrenamiento y prueba

El dataset se dividirá en dos grupos: 80% de los registros se utilizarán para entrenar los modelos y el 20% restante se reservará para evaluar su desempeño.

Además, se utilizará una división estratificada para mantener una proporción similar de clientes activos y cancelados en ambos conjuntos.
"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Datos de entrenamiento:", X_train.shape)
print("Datos de prueba:", X_test.shape)

print("\nDistribución en entrenamiento:")
print(y_train.value_counts())

print("\nDistribución en prueba:")
print(y_test.value_counts())

"""### 6. Entrenamiento de modelos de clasificación

#### Regresión Logística

La Regresión Logística se utilizará como primer modelo de clasificación para estimar la probabilidad de que un cliente cancele el servicio.

Este modelo permite trabajar con una variable objetivo binaria, en este caso `cancelo_servicio`, donde 0 representa que el cliente no canceló y 1 que sí canceló.
"""

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

modelo_logistico = Pipeline([
    ("preprocesamiento", preprocesador),
    ("modelo", LogisticRegression(max_iter=1000))
])

modelo_logistico.fit(X_train, y_train)

print("Modelo de Regresión Logística entrenado correctamente.")

"""#### Evaluación de la Regresión Logística

Una vez entrenado el modelo, se utilizará el conjunto de prueba para generar predicciones y compararlas con los valores reales.

Para evaluar su desempeño se utilizarán las métricas Accuracy, Precision, Recall y F1-Score. Estas métricas permiten analizar el comportamiento del modelo más allá del porcentaje general de predicciones correctas.
"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

y_pred_logistico = modelo_logistico.predict(X_test)

accuracy_logistico = accuracy_score(y_test, y_pred_logistico)
precision_logistico = precision_score(y_test, y_pred_logistico)
recall_logistico = recall_score(y_test, y_pred_logistico)
f1_logistico = f1_score(y_test, y_pred_logistico)

print("Resultados - Regresión Logística")
print("--------------------------------")
print(f"Accuracy:  {accuracy_logistico:.4f}")
print(f"Precision: {precision_logistico:.4f}")
print(f"Recall:    {recall_logistico:.4f}")
print(f"F1-Score:  {f1_logistico:.4f}")

"""#### Árbol de Decisión

Como segundo modelo se utilizará un Árbol de Decisión. Este algoritmo clasifica los registros mediante una serie de decisiones basadas en las características de los clientes.

Se utilizará una profundidad máxima limitada para evitar que el modelo se vuelva demasiado complejo y se ajuste excesivamente a los datos de entrenamiento.
"""

from sklearn.tree import DecisionTreeClassifier

modelo_arbol = Pipeline([
    ("preprocesamiento", preprocesador),
    ("modelo", DecisionTreeClassifier(
        random_state=42,
        max_depth=5
    ))
])

modelo_arbol.fit(X_train, y_train)

print("Modelo de Árbol de Decisión entrenado correctamente.")

"""#### Evaluación del Árbol de Decisión

Después de entrenar el Árbol de Decisión, se utilizará el conjunto de prueba para generar predicciones y compararlas con los valores reales.

Se emplearán las mismas métricas utilizadas en la Regresión Logística para poder realizar una comparación directa entre ambos modelos.
"""

y_pred_arbol = modelo_arbol.predict(X_test)

accuracy_arbol = accuracy_score(y_test, y_pred_arbol)
precision_arbol = precision_score(y_test, y_pred_arbol)
recall_arbol = recall_score(y_test, y_pred_arbol)
f1_arbol = f1_score(y_test, y_pred_arbol)

print("Resultados - Árbol de Decisión")
print("--------------------------------")
print(f"Accuracy:  {accuracy_arbol:.4f}")
print(f"Precision: {precision_arbol:.4f}")
print(f"Recall:    {recall_arbol:.4f}")
print(f"F1-Score:  {f1_arbol:.4f}")

"""#### Matriz de confusión del Árbol de Decisión

La matriz de confusión permite analizar con mayor detalle los aciertos y errores del modelo seleccionado, diferenciando los servicios correctamente clasificados de los falsos positivos y falsos negativos.
"""

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Crear matriz de confusión
matriz = confusion_matrix(y_test, y_pred_arbol)

# Mostrar matriz
disp = ConfusionMatrixDisplay(
    confusion_matrix=matriz,
    display_labels=["No canceló", "Canceló"]
)

disp.plot()
plt.title("Matriz de confusión - Árbol de Decisión")
plt.show()

print(matriz)

"""#### Interpretación de la matriz de confusión

El Árbol de Decisión fue evaluado utilizando 200 registros del conjunto de prueba. El modelo clasificó correctamente **142 servicios que no fueron cancelados** y logró identificar correctamente **23 de los 40 servicios que sí fueron cancelados**.

Por otra parte, se registraron **18 falsos positivos**, correspondientes a servicios que fueron clasificados como cancelaciones aunque realmente no cancelaron, y **17 falsos negativos**, que representan cancelaciones reales que el modelo no logró identificar.

Esto explica el Recall de **57.5%**, ya que el modelo detectó 23 de las 40 cancelaciones reales presentes en el conjunto de prueba. Los resultados muestran que el modelo puede utilizarse como herramienta de apoyo para priorizar clientes que requieren seguimiento, pero sus predicciones no deben interpretarse como una certeza de cancelación.

#### Random Forest

Como tercer modelo se utilizará Random Forest. Este algoritmo combina múltiples árboles de decisión y utiliza el resultado conjunto de estos árboles para realizar la clasificación.

El objetivo de utilizar varios árboles es reducir la dependencia de un solo modelo y obtener predicciones más estables.
"""

from sklearn.ensemble import RandomForestClassifier

modelo_rf = Pipeline([
    ("preprocesamiento", preprocesador),
    ("modelo", RandomForestClassifier(
        n_estimators=200,
        random_state=42
    ))
])

modelo_rf.fit(X_train, y_train)

print("Modelo Random Forest entrenado correctamente.")

"""#### Evaluación de Random Forest

Después de entrenar el modelo Random Forest, se utilizará el conjunto de prueba para generar predicciones.

Los resultados se evaluarán con Accuracy, Precision, Recall y F1-Score, utilizando las mismas métricas aplicadas a los modelos anteriores.
"""

y_pred_rf = modelo_rf.predict(X_test)

accuracy_rf = accuracy_score(y_test, y_pred_rf)
precision_rf = precision_score(y_test, y_pred_rf)
recall_rf = recall_score(y_test, y_pred_rf)
f1_rf = f1_score(y_test, y_pred_rf)

print("Resultados - Random Forest")
print("--------------------------")
print(f"Accuracy:  {accuracy_rf:.4f}")
print(f"Precision: {precision_rf:.4f}")
print(f"Recall:    {recall_rf:.4f}")
print(f"F1-Score:  {f1_rf:.4f}")

"""#### Comparación de los modelos

Después de evaluar los tres modelos, se compararán sus métricas para analizar sus diferencias y determinar cuál presenta un comportamiento más adecuado para el objetivo del proyecto.
"""

import pandas as pd

comparacion_modelos = pd.DataFrame({
    "Modelo": [
        "Regresión Logística",
        "Árbol de Decisión",
        "Random Forest"
    ],
    "Accuracy": [
        accuracy_logistico,
        accuracy_arbol,
        accuracy_rf
    ],
    "Precision": [
        precision_logistico,
        precision_arbol,
        precision_rf
    ],
    "Recall": [
        recall_logistico,
        recall_arbol,
        recall_rf
    ],
    "F1-Score": [
        f1_logistico,
        f1_arbol,
        f1_rf
    ]
})

comparacion_modelos

"""#### Selección del modelo final

Después de comparar los tres modelos, se seleccionó el Árbol de Decisión como modelo principal para el proyecto.

Aunque Random Forest obtuvo el mayor Accuracy y Precision, el Árbol de Decisión presentó el mayor Recall y F1-Score. Esto significa que logró identificar una mayor proporción de los clientes que realmente cancelaron el servicio y mantuvo un mejor equilibrio entre la detección de cancelaciones y las falsas alertas.

Debido a que el objetivo de NewLinkWireless es identificar clientes con riesgo de cancelación para poder tomar acciones preventivas, se consideró más importante priorizar la capacidad de detección de cancelaciones reales.

### 7. Generación de resultados para Power BI

Después de seleccionar el Árbol de Decisión como modelo final, se utilizará el dataset completo para generar una estimación del riesgo de cancelación de cada servicio.

Los resultados incluirán la probabilidad estimada de cancelación, la predicción del modelo y una clasificación de riesgo en tres niveles: Bajo, Medio y Alto.
"""

from sklearn.base import clone

modelo_final_completo = clone(modelo_arbol)

modelo_final_completo.fit(X, y)

print("Modelo final entrenado con el dataset completo.")

df_resultados = df.copy()

df_resultados["probabilidad_cancelacion"] = (
    modelo_final_completo.predict_proba(X)[:, 1]
)

df_resultados["prediccion_cancelacion"] = (
    modelo_final_completo.predict(X)
)

df_resultados.head()

def clasificar_riesgo(probabilidad):
    if probabilidad < 0.30:
        return "Bajo"
    elif probabilidad < 0.60:
        return "Medio"
    else:
        return "Alto"

df_resultados["nivel_riesgo"] = (
    df_resultados["probabilidad_cancelacion"]
    .apply(clasificar_riesgo)
)

df_resultados[
    [
        "id_servicio",
        "probabilidad_cancelacion",
        "prediccion_cancelacion",
        "nivel_riesgo"
    ]
].head(10)

print("Distribución por nivel de riesgo:")
print(df_resultados["nivel_riesgo"].value_counts())

print("\nPredicción de cancelación:")
print(df_resultados["prediccion_cancelacion"].value_counts())

df_resultados.to_csv(
    "/content/dataset_resultados_modelo_newlinkwireless.csv",
    index=False,
    encoding="utf-8-sig"
)

print("CSV generado correctamente.")
print("Dimensiones:", df_resultados.shape)